name: Medvoll - CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  java-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: medvoll
    strategy:
      max-parallel: 4
      matrix:
        java-versions:
          - 25

    steps:
      - uses: actions/checkout@v5
      - name: Configurando ambiente para o Java 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: oracle
          cache: maven
      - name: Configurando settings.xml do Maven
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          plugin_groups: '["io.spring.javaformat"]'
      - name: Instalando pacotes com Maven
        run: ./mvnw -DskipTests clean install --file pom.xml
      - name: Validar formatação Spring JavaFormat
        run: ./mvnw spring-javaformat:validate
