name: Medvoll - CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
    
jobs:
  java-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: medvoll
    strategy:
      max-parallel: 4
      matrix:
        java-versions:
          - 25
          
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: openjdk
          cache: maven
      - name: Cache das dependÃªncias Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('medvoll/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build com Maven
        run: ./mvnw -DskipTests clean install --file medvoll/pom.xml
