---
name: Medvoll - CI
on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: medvoll
    strategy:
      max-parallel: 4
      matrix:
        java-versions:
          - 25
  steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setando a versão do Java 25
      uses: actions/setup-java@v5
      with:
        java-version: 25
        distribution: openjdk
        cache: maven
    - name: Cache das dependências Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('medvoll/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build com Maven
      run: ./mvnw -DskipTests clean install --file medvoll/pom.xml
